version: "3.8"

services:
  app:
    build: .
    ports:
      - "3001:3001"
    restart: always
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=https://epay.co.id
      - NEXT_PUBLIC_NEXTAUTH_URL=https://epay.co.id
